GET http://localhost:3000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSHJpc2hpIiwiaWF0IjoxNzkwNzEwMzIxLCJleHAiOjE3OTA3MTAzNDF9.T0xQOVK6dN-SaVSP8bswvkxRsJsJZ_pm-nAX5vOSeZM
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "userName":"Hrishi"
}

###

POST http://localhost:4000/token
Content-Type: application/json


{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSHJpc2hpIiwiaWF0IjoxNzkwNzEwMjYwfQ.H6zEupJFZPN7Ki3KRbvbXHMQzn1zqa2_Zst9OlJkq1Y"
}
